#!/bin/bash
# Date and clicable Calendar
# Panos Fykouras
# panosfykouras@gmail.com

date '+%d-%m-%Y'

[[ $BLOCK_BUTTON = "1" ]] && xterm -geometry 20x9+1790+0 -bg black -fg white -hold -e 'cal' &





